language: python
python:
- '3.6'
install:
- pip install --upgrade pip
- export PATH=$HOME/.local/bin:$PATH
- pip install -r requirements.txt
script: make manual
deploy:
  provider: s3
  on:
    all_branches: true
  access_key_id:
    secure: 1SalBj/oDu8HAKp2EIZwWPskO1uuIgT+wkXPNuRClfLoG56g+0sz/u9N9J9zzvks24xIQLotVK5u6s4Jv8F9GRSec6C8mdiyDhX2t+RLXC7H9PvYmoM1z5aye3SRkNBWnJMqnneYD67GuKCB0MoIeC9r6HI5Zn4BeviMjiw53C4BwK4oIpONRrwV4VOqBf8UTJGYM9jq9PkRv3pHhSgVQaaTFck5FCyql+bzCYhW9++U41e8xUTWk3g212dW2sRo5NnUMODU0wRkjC9oLB2V24cn9lNHra15IznMkvPPr4xSrmtnQ2+bmVJBWL5pivjisVhVoMP2xCwg31m9lM8JFl4vmoI63FhK0zjsW0Kx3tKArXhUzutTJTVGGZLFkehRYW9rX1Crw9SUYj0jtKQwUanHeerRM0KGeg7dQnbEsfI8R6CsZOuNzsd7yScjv+3fMdyb668yIfgZrZQXvUTvciuA+UJsvBOKdsFMam/edk5tEUti74cdf/O4hBLbs9H0tRoR70Vf1KM88mHIKK4GEZ0/X3jxHZPK+VZNwEs/jgG8XOkq8YcpRl1bGLrfOOcHal/1x0cFYronjWAWAN4fpIagzWiO0Ipl566So2nN8lZ4+U5abjLsR3xVcezlbKSZ2nIMSTCraI3evNo0y8UOvWD54V361hgWBO9wyR7nXtk=
  secret_access_key:
    secure: YEHj7ocOrAgeLjkmgJQTI9ztzW8RQOawlAviiyaWF5ui3B1vPAj1snPyMzmENMc1+fYMMIPWaml9o5XdRBlH85TazCDUaJO9TNvDSDd5b44xYB36SdAm3n88KMzmLF9iBqh4SbczNRTojhULngsl+tio77U7kjo00OB7n5AkFjhASfuG5HDlCjRQeypTbET0AtQ18pbLEwU1I/KGygyEQafP19veN9zW5ClXBKcEKxfCyw84Q/dWOJ9UEzfwlDE392UkC/q0BAn90iplFOsaj1MKT68M6wLSp6jYKWZ08aPUoL4Y/+CfZQLcg1N50/+gCUZcxZiH8YIaVOPVonrL5UeDbFcpKfygP83FZS8D52ZtHYy0YzemhEZdtdYV2rPZE5HohquU5ev6eiiGSCHajCTuXCetNtjfdhzOq4qlAO/YKq/bXT9fnzqPJ6yvH8WNUsC3mE9pq3cHXexzDGgLfeTg0r3Swt33DKba8G/zavU7znqsp6IV6ePqty3aB2iyzarZ2QC4rmAo9e7+A4kdIaJbuDXv5Kod9Um/JPciqbuh75izqZ3k7myHTy67IUzodnjCMfdfIehtnLyzmBiDeSGl7bzZS8ZGsJzksQ+SnMzZq5b5nBmi0txC7HgJq3GJtvPl31M+mWJ3GbRFU3Br34L01LPUjrs++BxfEgO1HTo=
  bucket:
    secure: sL+D0Nr96t+WO/kNb3f82asJrJowk84pkhPO3YOidr1hrNhOqeL6AY1mHGIiE00blNRYdnYfLFNERTu+lwb9jjidVt0DYImU3JvE2v0C/H5NKLfQC3Ox2XDAWVlIvTdtNL0BjXkoEXB5ze2OQOdVDDCUtV3fiVbiaLkRXbOKwu/EoLzPs5K1BsEt1fCBesbONeTaCSyXS9Jfmiwb1sMpnYMU5xh9ZFQb5ed7LMBlSyTB+z+dYl5j0c/r+nNXfRcv5BYM2LvPKrj1N11vPzc4n8tT7WkVA+w0iLceELba4Tzbw9uxSE7mkTXp2BOyAhHI+4wvbHu/P2SPqZtW3eRGoRTbMrAzgRC5zZ/DkyVNvJmJKX9jVcR9D+EbBRkZNbpfwvVLGT89DvX8oBcbMYxlnGTIyBpNtzje6FC5L8IsoFwgbgjKwO66f8oOYlUU1lEw5V74tsJybv2P6RHzYsh7ltvtPR/hpXpQhytBsjj+Ork0ePLlt8W1dt5nHYk7tuKSBlrn438pu2BjHLvmGz2gGu4V975HZ67GVdBtDYlZ9bv8X9q77AyVjn9uETxF4vthkzmfwgBbBhhSm8DMBYGaGo2DlGeA5YwFMfzhxT6zj4yu7/KddlZoUYPTNPV8v+uC++N8Hr1OmsoTkSsXYOmipphRd0nBqGzZAyHEio+BhMo=
  upload_dir: lambdas
  server_side_encryption: true
  local_dir: build
  region: us-west-2
  skip_cleanup: true
notifications:
  slack:
    secure: k2Q3xTX0Vg2sLiCaIhq1/zB2lNvfyprLZfruxhHZTahY6x5121lCYYWxdZxZYCAKP+bhyhoCu6STZVzsDMQbWbH1bObqBBR/jSkd4Voi8NUBWcSRMaeSskDi3GI5MA8+FoJTvEr3KZY3EteLS1mPwisx0LwFnV99t9/wu2jJT5pSKSgZp35rIIs8qpGAKq+m/DXTpTPnLKXKvtG9yCNmXksXq+Znhel2YsyI8IV/EdMcDliClcAadQ5NB93T1pQCGx7VFZDMKxutXRRNFQoC7O9CueN9oWrPD1YlemS5ZeW5Y/a0FwmcvMnpGcYSSPE2nGrq1CILHLWWbs7QgRYQoNBkBX9yBBk+dcMUPzTNH1lIgbXPEnYUoVGYFhwjaN+E3MARVTiwOV/6A+iWq6HGPVwMHn6ypbS6tckolU7NkV9llz4YR9GxHE+JOiIBgaMr54LK8+tSl7AmFe2R8ZAG+FI6cXkrI3RWyOC/QT+S8XbrfQyyVZ8fD63Jd/lqUesdAvYFzxDn5sgaO6MNnhaYMrjfxqmVKImspAlWNqVf9o9G+thgjnIljJIY6BRub0RLKreWWibm8ESjpJy2kFp7xaIyWMUXaV36QIlseQ+nR3Lhd7iCnvMrMqReORduywZFE0WursQbjT+DBaEV8AsWt3SEMvtUUzKwKxzKnnDCwGQ=
